import { DollarSign, Download, RefreshCw } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

import { BackupsIntake, BackupsReviewDestination } from "../api/backups";
import { mediaApi } from "../api/media";
import { UniversalPhotoField } from "../components/UniversalPhotoField";
import { ReceiptCapturePanel } from "../components/ReceiptCapturePanel";
import { CustomerInvoicePanel } from "../components/CustomerInvoicePanel";
import { financeApi, FinancialSummary, StartupExpenseSummary } from "../api/finance";
import { projectsApi, Project } from "../api/projects";

const money = new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD" });
const today = () => new Date().toISOString().slice(0, 10);

export function FinancialControlPage() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [projectId, setProjectId] = useState("");
  const [summary, setSummary] = useState<FinancialSummary | null>(null);
  const [startup, setStartup] = useState<StartupExpenseSummary | null>(null);
  const [backupsReview, setBackupsReview] = useState<Record<string, BackupsIntake[]>>({});
  const [entryType, setEntryType] = useState("actual"); const [category, setCategory] = useState("material"); const [costCode, setCostCode] = useState(""); const [amount, setAmount] = useState(""); const [vendor, setVendor] = useState(""); const [reference, setReference] = useState(""); const [description, setDescription] = useState(""); const [entryDate, setEntryDate] = useState(today());
  const [startupDate, setStartupDate] = useState(today()); const [startupVendor, setStartupVendor] = useState(""); const [startupDescription, setStartupDescription] = useState(""); const [startupAmount, setStartupAmount] = useState(""); const [startupCategory, setStartupCategory] = useState("other"); const [startupReference, setStartupReference] = useState(""); const [startupOwner, setStartupOwner] = useState("");
  const [startupFiles, setStartupFiles] = useState<File[]>([]);
  const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { projectsApi.list().then((data) => setProjects(data.items)).catch(() => setError("Unable to load projects.")); void refreshStartup(); void refreshBackupsReview(); }, []);
  async function refresh(id = projectId) { if (!id) return; setLoading(true); setError(null); try { setSummary(await financeApi.getProject(id)); } catch (current) { setError(current instanceof Error ? current.message : "Unable to load financials."); } finally { setLoading(false); } }
  async function refreshStartup() { try { setStartup(await financeApi.getStartupExpenses()); } catch (current) { setError(current instanceof Error ? current.message : "Unable to load startup costs."); } }
  async function refreshBackupsReview() { const destinations: BackupsReviewDestination[] = ["finance_intake", "finance_receipts", "finance_invoices", "finance_packing_slips"]; try { const queues = await Promise.all(destinations.map(async (destination) => [destination, (await financeApi.getBackupsReview(destination)).items] as const)); setBackupsReview(Object.fromEntries(queues)); } catch (current) { setError(current instanceof Error ? current.message : "Unable to load Backups review queues."); } }
  async function importBudget() { if (!projectId) return; setLoading(true); setError(null); try { setSummary(await financeApi.importEstimate(projectId)); } catch (current) { setError(current instanceof Error ? current.message : "Unable to import estimate."); } finally { setLoading(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (!projectId || !costCode || !amount) return; setLoading(true); setError(null); try { await financeApi.createEntry({ project_id: projectId, cost_code: costCode, entry_type: entryType, category, amount: Number(amount), entry_date: entryDate, vendor_name: vendor || null, reference: reference || null, description: description || null, status: entryType === "commitment" ? "open" : "posted" }); setAmount(""); setReference(""); setDescription(""); await refresh(); } catch (current) { setError(current instanceof Error ? current.message : "Unable to save financial entry."); } finally { setLoading(false); } }
  async function submitStartup(event: FormEvent) { event.preventDefault(); if (!startupVendor || !startupDescription || !startupAmount) return; setLoading(true); setError(null); try { const photos = startupFiles.length ? await mediaApi.upload({ files: startupFiles, caption: startupDescription, capturedDate: startupDate, category: "receipt" }) : []; const expense = await financeApi.createStartupExpense({ expense_date: startupDate, vendor_name: startupVendor, description: startupDescription, amount: Number(startupAmount), category: startupCategory, reference: startupReference || null, funding_source: "owner_loan", owner_name: startupOwner || null, tax_treatment: "needs_review", status: "review", receipt_metadata: { intake: "manual_or_email_receipt", document_ids: photos.map((photo) => photo.original_document_id) } }); await Promise.all(photos.map((photo) => mediaApi.link(photo.id, "startup_expense", expense.id))); setStartupVendor(""); setStartupDescription(""); setStartupAmount(""); setStartupReference(""); setStartupFiles([]); await refreshStartup(); } catch (current) { setError(current instanceof Error ? current.message : "Unable to save startup expense. Selected receipts were retained for retry."); } finally { setLoading(false); } }
  async function setStartupStatus(id: string, status: "approved" | "reimbursed" | "void") { setLoading(true); setError(null); try { await financeApi.updateStartupExpense(id, { status }); await refreshStartup(); } catch (current) { setError(current instanceof Error ? current.message : "Unable to update startup expense."); } finally { setLoading(false); } }
  return <section className="space-y-6">
    <div className="flex flex-col gap-4 border-b border-iron-100 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-semibold text-iron-950">Financial Control</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-iron-500">Management-only project financials plus corporate startup costs funded by owners and tracked as an Owner/Shareholder Loan Payable until reimbursement.</p></div><div className="flex gap-2"><button onClick={() => { void refresh(); void refreshStartup(); void refreshBackupsReview(); }} className="inline-flex items-center gap-2 rounded-md border border-iron-100 bg-white px-3 py-2 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</button><a href={financeApi.startupQuickBooksUrl()} className="inline-flex items-center gap-2 rounded-md bg-brand-gold px-3 py-2 text-sm font-semibold text-brand-black"><Download className="h-4 w-4" />Startup CSV</a>{projectId ? <a href={financeApi.quickBooksUrl(projectId)} className="inline-flex items-center gap-2 rounded-md bg-brand-gold px-3 py-2 text-sm font-semibold text-brand-black"><Download className="h-4 w-4" />Project CSV</a> : null}</div></div>
    {error ? <div role="alert" className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div> : null}

    <ReceiptCapturePanel reviewer />

    <CustomerInvoicePanel />

    <BackupsReviewQueues queues={backupsReview} />

    <div className="rounded-md border border-iron-100 bg-white p-5"><div className="flex items-center gap-2"><DollarSign className="h-4 w-4" /><h2 className="font-semibold">Startup costs / owner loan</h2></div><p className="mt-2 text-sm text-iron-500">Use for legitimate company startup purchases paid personally. Review first, approve business expenses, then mark reimbursed only when the company actually repays the owner.</p>{startup ? <div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Metric label="Startup costs" value={money.format(startup.total_startup_costs)} /><Metric label="Owner loan payable" value={money.format(startup.owner_loan_payable)} /><Metric label="Approved unpaid" value={money.format(startup.approved_unreimbursed)} /><Metric label="Pending review" value={money.format(startup.pending_review)} /><Metric label="Reimbursed" value={money.format(startup.reimbursed_to_owner)} /></div> : null}
      <form onSubmit={submitStartup} className="mt-5 border-t border-iron-100 pt-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Input label="Date" value={startupDate} onChange={setStartupDate} type="date" /><Input label="Vendor" value={startupVendor} onChange={setStartupVendor} /><Input label="Description" value={startupDescription} onChange={setStartupDescription} /><Input label="Amount CAD" value={startupAmount} onChange={setStartupAmount} type="number" /><Select label="Category" value={startupCategory} onChange={setStartupCategory} options={["software","office","vehicle","tools","equipment","professional","insurance","registration","marketing","communications","other"].map((x) => [x,x])} /><Input label="Receipt / order reference" value={startupReference} onChange={setStartupReference} /><Input label="Owner / shareholder" value={startupOwner} onChange={setStartupOwner} /><UniversalPhotoField files={startupFiles} onFilesChange={setStartupFiles} category="receipt" label="Receipts" /></div><button disabled={loading || !startupVendor || !startupDescription || !startupAmount} className="mt-4 rounded-md bg-brand-gold px-4 py-2 text-sm font-semibold text-brand-black disabled:opacity-50">Add to review</button></form>
      {startup?.entries.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[960px] text-left text-sm"><thead className="bg-iron-50 text-xs uppercase text-iron-500"><tr><th className="px-4 py-3">Date</th><th>Vendor</th><th>Description</th><th>Amount</th><th>Funding</th><th>Tax</th><th>Status</th><th>Actions</th></tr></thead><tbody>{startup.entries.map((row) => <tr key={row.id} className="border-t border-iron-100"><td className="px-4 py-3">{row.expense_date}</td><td>{row.vendor_name}</td><td>{row.description}</td><td>{money.format(row.amount)}</td><td>{row.funding_source === "owner_loan" ? "Owner loan" : "Company"}</td><td>{row.tax_treatment.replaceAll("_", " ")}</td><td>{row.status}</td><td><UniversalPhotoField recordType="startup_expense" recordId={row.id} category="receipt" label="Receipt evidence" /><div className="flex gap-2">{row.status === "review" ? <button onClick={() => void setStartupStatus(row.id, "approved")} className="text-sm font-semibold underline">Approve</button> : null}{row.status === "approved" ? <button onClick={() => void setStartupStatus(row.id, "reimbursed")} className="text-sm font-semibold underline">Reimbursed</button> : null}{row.status !== "reimbursed" ? <button onClick={() => void setStartupStatus(row.id, "void")} className="text-sm text-red-700 underline">Void</button> : null}</div></td></tr>)}</tbody></table></div> : null}
    </div>

    <div className="rounded-md border border-iron-100 bg-white p-5"><label className="text-sm font-semibold">Project<select value={projectId} onChange={(event) => { setProjectId(event.target.value); setSummary(null); void refresh(event.target.value); }} className="mt-2 w-full rounded-md border border-iron-100 px-3 py-2"><option value="">Select project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><button onClick={() => void importBudget()} disabled={!projectId || loading} className="mt-3 rounded-md bg-brand-gold px-4 py-2 text-sm font-semibold text-brand-black disabled:opacity-50">Import latest estimate as budget</button></div>
    {summary ? <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Contract / revenue" value={money.format(summary.contract_value)} /><Metric label="Cost budget" value={money.format(summary.budget)} /><Metric label="Committed + actual" value={money.format(summary.committed + summary.actual)} /><Metric label={`Forecast margin ${summary.forecast_margin_percent}%`} value={money.format(summary.forecast_profit)} /></div>
    <form onSubmit={submit} className="rounded-md border border-iron-100 bg-white p-5"><div className="flex items-center gap-2"><DollarSign className="h-4 w-4" /><h2 className="font-semibold">Add project financial entry</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Select label="Type" value={entryType} onChange={setEntryType} options={[["commitment","Committed cost / PO"],["actual","Actual cost / invoice"],["revenue","Revenue / progress claim"],["forecast_adjustment","Forecast adjustment"]]} /><Select label="Category" value={category} onChange={setCategory} options={["labour","equipment","material","trucking","subcontract","rental","fuel","overhead","contingency","bonding","insurance","other"].map((x) => [x,x])} /><Input label="Cost code" value={costCode} onChange={setCostCode} /><Input label="Amount CAD" value={amount} onChange={setAmount} type="number" /><Input label="Date" value={entryDate} onChange={setEntryDate} type="date" /><Input label="Vendor" value={vendor} onChange={setVendor} /><Input label="PO / invoice / claim reference" value={reference} onChange={setReference} /><Input label="Description" value={description} onChange={setDescription} /></div><button disabled={loading || !costCode || !amount} className="mt-4 rounded-md bg-brand-gold px-4 py-2 text-sm font-semibold text-brand-black disabled:opacity-50">Post entry</button></form>
    <div className="overflow-x-auto rounded-md border border-iron-100 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-iron-50 text-xs uppercase text-iron-500"><tr><th className="px-4 py-3">Cost code</th><th>Budget</th><th>Committed</th><th>Actual</th><th>Forecast</th><th>Variance</th></tr></thead><tbody>{summary.cost_codes.map((row) => <tr key={row.cost_code} className="border-t border-iron-100"><td className="px-4 py-3 font-semibold">{row.cost_code}</td><td>{money.format(row.budget)}</td><td>{money.format(row.committed)}</td><td>{money.format(row.actual)}</td><td>{money.format(row.forecast)}</td><td className={row.variance < 0 ? "text-red-700" : "text-emerald-700"}>{money.format(row.variance)}</td></tr>)}</tbody></table></div></> : null}
  </section>;
}
function BackupsReviewQueues({ queues }: { queues: Record<string, BackupsIntake[]> }) {
  const sections: Array<[BackupsReviewDestination, string, string]> = [
    ["finance_intake", "Finance intake", "Analyzed Backups photos awaiting management routing."],
    ["finance_receipts", "Receipts", "Review-only receipt photos; approval and export remain separate controlled actions."],
    ["finance_invoices", "Invoices", "Review-only supplier invoice photos; routing does not post or pay them."],
    ["finance_packing_slips", "Packing Slips", "Review-only evidence; quantity, quality, delivery acceptance, and project cost are not confirmed."],
  ];
  return <section className="rounded-md border border-iron-100 bg-white p-5"><h2 className="font-semibold text-iron-950">Backups review queues</h2><p className="mt-1 text-sm text-iron-500">Queue placement is review-only and never performs a financial or delivery action.</p><div className="mt-4 grid gap-4 lg:grid-cols-2">{sections.map(([destination, label, description]) => <section key={destination} className="rounded-md border border-iron-100 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{label}</h3><p className="mt-1 text-xs leading-5 text-iron-500">{description}</p></div><span className="rounded-full bg-iron-100 px-2.5 py-1 text-xs font-semibold">{queues[destination]?.length ?? 0}</span></div><div className="mt-3 grid gap-2">{queues[destination]?.map((item) => <article key={item.id} className="grid grid-cols-[64px_1fr] gap-3 rounded-md bg-iron-50 p-2"><a href={mediaApi.contentUrl(item.media_id)} target="_blank" rel="noreferrer"><img src={mediaApi.contentUrl(item.media_id)} alt={`Private Backups ${label} original`} className="h-16 w-16 rounded-md object-cover" /></a><div className="min-w-0 text-xs text-iron-600"><div className="font-semibold text-iron-900">{item.detected_type?.replaceAll("_", " ") ?? "Unknown type"}</div><div className="mt-1 truncate">{item.uploader_email}</div>{item.project_hint ? <div className="mt-1 truncate">Project hint: {item.project_hint}</div> : null}</div></article>)}{!queues[destination]?.length ? <div className="rounded-md bg-iron-50 p-3 text-xs text-iron-500">No items in this queue.</div> : null}</div></section>)}</div></section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-md border border-iron-100 bg-white p-5"><div className="text-sm text-iron-500">{label}</div><div className="mt-3 text-2xl font-semibold">{value}</div></div>; }
function Input({ label, value, onChange, type="text" }: { label:string; value:string; onChange:(v:string)=>void; type?:string }) { return <label className="text-sm font-semibold">{label}<input type={type} value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 w-full rounded-md border border-iron-100 px-3 py-2 font-normal" /></label>; }
function Select({ label, value, onChange, options }: { label:string; value:string; onChange:(v:string)=>void; options:string[][] }) { return <label className="text-sm font-semibold">{label}<select value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 w-full rounded-md border border-iron-100 px-3 py-2 font-normal">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>; }
