import { DollarSign, Download, RefreshCw } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

import { financeApi, FinancialSummary } from "../api/finance";
import { projectsApi, Project } from "../api/projects";

const money = new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD" });
const today = () => new Date().toISOString().slice(0, 10);

export function FinancialControlPage() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [projectId, setProjectId] = useState("");
  const [summary, setSummary] = useState<FinancialSummary | null>(null);
  const [entryType, setEntryType] = useState("actual"); const [category, setCategory] = useState("material"); const [costCode, setCostCode] = useState(""); const [amount, setAmount] = useState(""); const [vendor, setVendor] = useState(""); const [reference, setReference] = useState(""); const [description, setDescription] = useState(""); const [entryDate, setEntryDate] = useState(today());
  const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { projectsApi.list().then((data) => setProjects(data.items)).catch(() => setError("Unable to load projects.")); }, []);
  async function refresh(id = projectId) { if (!id) return; setLoading(true); setError(null); try { setSummary(await financeApi.getProject(id)); } catch (current) { setError(current instanceof Error ? current.message : "Unable to load financials."); } finally { setLoading(false); } }
  async function importBudget() { if (!projectId) return; setLoading(true); setError(null); try { setSummary(await financeApi.importEstimate(projectId)); } catch (current) { setError(current instanceof Error ? current.message : "Unable to import estimate."); } finally { setLoading(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (!projectId || !costCode || !amount) return; setLoading(true); setError(null); try { await financeApi.createEntry({ project_id: projectId, cost_code: costCode, entry_type: entryType, category, amount: Number(amount), entry_date: entryDate, vendor_name: vendor || null, reference: reference || null, description: description || null, status: entryType === "commitment" ? "open" : "posted" }); setAmount(""); setReference(""); setDescription(""); await refresh(); } catch (current) { setError(current instanceof Error ? current.message : "Unable to save financial entry."); } finally { setLoading(false); } }
  return <section className="space-y-6">
    <div className="flex flex-col gap-4 border-b border-iron-100 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-semibold text-iron-950">Financial Control</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-iron-500">Management-only project budgets, commitments, actual costs, forecast margin, and QuickBooks cross-reference.</p></div><div className="flex gap-2"><button onClick={() => void refresh()} className="inline-flex items-center gap-2 rounded-md border border-iron-100 bg-white px-3 py-2 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</button>{projectId ? <a href={financeApi.quickBooksUrl(projectId)} className="inline-flex items-center gap-2 rounded-md bg-brand-gold px-3 py-2 text-sm font-semibold text-brand-black"><Download className="h-4 w-4" />QuickBooks CSV</a> : null}</div></div>
    {error ? <div role="alert" className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div> : null}
    <div className="rounded-md border border-iron-100 bg-white p-5"><label className="text-sm font-semibold">Project<select value={projectId} onChange={(event) => { setProjectId(event.target.value); setSummary(null); void refresh(event.target.value); }} className="mt-2 w-full rounded-md border border-iron-100 px-3 py-2"><option value="">Select project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><button onClick={() => void importBudget()} disabled={!projectId || loading} className="mt-3 rounded-md bg-brand-gold px-4 py-2 text-sm font-semibold text-brand-black disabled:opacity-50">Import latest estimate as budget</button></div>
    {summary ? <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Contract / revenue" value={money.format(summary.contract_value)} /><Metric label="Cost budget" value={money.format(summary.budget)} /><Metric label="Committed + actual" value={money.format(summary.committed + summary.actual)} /><Metric label={`Forecast margin ${summary.forecast_margin_percent}%`} value={money.format(summary.forecast_profit)} /></div>
    <form onSubmit={submit} className="rounded-md border border-iron-100 bg-white p-5"><div className="flex items-center gap-2"><DollarSign className="h-4 w-4" /><h2 className="font-semibold">Add financial entry</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Select label="Type" value={entryType} onChange={setEntryType} options={[["commitment","Committed cost / PO"],["actual","Actual cost / invoice"],["revenue","Revenue / progress claim"],["forecast_adjustment","Forecast adjustment"]]} /><Select label="Category" value={category} onChange={setCategory} options={["labour","equipment","material","trucking","subcontract","rental","fuel","overhead","contingency","bonding","insurance","other"].map((x) => [x,x])} /><Input label="Cost code" value={costCode} onChange={setCostCode} /><Input label="Amount CAD" value={amount} onChange={setAmount} type="number" /><Input label="Date" value={entryDate} onChange={setEntryDate} type="date" /><Input label="Vendor" value={vendor} onChange={setVendor} /><Input label="PO / invoice / claim reference" value={reference} onChange={setReference} /><Input label="Description" value={description} onChange={setDescription} /></div><button disabled={loading || !costCode || !amount} className="mt-4 rounded-md bg-brand-gold px-4 py-2 text-sm font-semibold text-brand-black disabled:opacity-50">Post entry</button></form>
    <div className="overflow-x-auto rounded-md border border-iron-100 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-iron-50 text-xs uppercase text-iron-500"><tr><th className="px-4 py-3">Cost code</th><th>Budget</th><th>Committed</th><th>Actual</th><th>Forecast</th><th>Variance</th></tr></thead><tbody>{summary.cost_codes.map((row) => <tr key={row.cost_code} className="border-t border-iron-100"><td className="px-4 py-3 font-semibold">{row.cost_code}</td><td>{money.format(row.budget)}</td><td>{money.format(row.committed)}</td><td>{money.format(row.actual)}</td><td>{money.format(row.forecast)}</td><td className={row.variance < 0 ? "text-red-700" : "text-emerald-700"}>{money.format(row.variance)}</td></tr>)}</tbody></table></div></> : null}
  </section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-md border border-iron-100 bg-white p-5"><div className="text-sm text-iron-500">{label}</div><div className="mt-3 text-2xl font-semibold">{value}</div></div>; }
function Input({ label, value, onChange, type="text" }: { label:string; value:string; onChange:(v:string)=>void; type?:string }) { return <label className="text-sm font-semibold">{label}<input type={type} value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 w-full rounded-md border border-iron-100 px-3 py-2 font-normal" /></label>; }
function Select({ label, value, onChange, options }: { label:string; value:string; onChange:(v:string)=>void; options:string[][] }) { return <label className="text-sm font-semibold">{label}<select value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 w-full rounded-md border border-iron-100 px-3 py-2 font-normal">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>; }
