#!/usr/bin/env python3
"""Iron House Autonomous Foreman v2.

Plan-first autonomous development coordinator.

The Foreman reads the roadmap, role definitions, and backlog, selects the
highest-priority open task, creates an implementation plan, writes run output,
and optionally calls an external coder command.

Default mode is safe plan-only. It does not submit bids, send emails, spend
money, merge pull requests, or approve contracts.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
ROADMAP_PATH = ROOT / "ROADMAP.md"
BACKLOG_PATH = ROOT / "automation" / "autonomous_backlog.json"
ROLES_PATH = ROOT / "automation" / "agent_roles.json"
OUTPUT_PATH = ROOT / "automation" / "foreman-output.json"
PLAN_PATH = ROOT / "automation" / "foreman-next-plan.md"


def main() -> int:
    roadmap = ROADMAP_PATH.read_text(encoding="utf-8") if ROADMAP_PATH.exists() else ""
    backlog = _read_json(BACKLOG_PATH)
    roles = _read_json(ROLES_PATH)
    task = _select_next_task(backlog)

    if task is None:
        _write_json(OUTPUT_PATH, {"status": "idle", "message": "No open backlog tasks."})
        print("No open backlog tasks.")
        return 0

    plan = _build_plan(task, roles, roadmap)
    PLAN_PATH.write_text(plan, encoding="utf-8")

    command = os.getenv("IH_CODER_COMMAND")
    mode = os.getenv("IH_FOREMAN_MODE", "plan-only")
    coder_exit_code: int | None = None

    if command and mode == "execute":
        result = subprocess.run(
            command,
            shell=True,
            cwd=ROOT,
            check=False,
            env={
                **os.environ,
                "IH_FOREMAN_TASK_JSON": json.dumps(task),
                "IH_FOREMAN_PLAN_FILE": str(PLAN_PATH),
            },
        )
        coder_exit_code = result.returncode

    payload = {
        "status": "planned" if coder_exit_code is None else "executed",
        "mode": mode,
        "task": task,
        "plan_file": str(PLAN_PATH.relative_to(ROOT)),
        "coder_exit_code": coder_exit_code,
        "timestamp_utc": datetime.now(UTC).isoformat(),
    }
    _write_json(OUTPUT_PATH, payload)
    print(plan)
    return 0 if coder_exit_code is None else coder_exit_code


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def _select_next_task(backlog: dict[str, Any]) -> dict[str, Any] | None:
    tasks = [task for task in backlog.get("tasks", []) if task.get("status") == "open"]
    if not tasks:
        return None
    return sorted(tasks, key=lambda task: int(task.get("priority", 9999)))[0]


def _build_plan(task: dict[str, Any], roles: dict[str, Any], roadmap: str) -> str:
    role_names = ", ".join(task.get("agents", []))
    criteria = "\n".join(f"- {item}" for item in task.get("acceptance_criteria", []))
    role_summary = "\n".join(f"- {role['name']}: {role['purpose']}" for role in roles.get("roles", []))
    return f"""# GO: {task['title']}

Generated by Iron House Autonomous Foreman v2.

## Task

ID: `{task['id']}`

Priority: {task.get('priority')}

{task.get('summary', '')}

## Assigned Agents

{role_names}

## Acceptance Criteria

{criteria}

## Implementation Plan

1. Architect agent reviews existing backend routes, schemas, frontend pages, and module navigation.
2. Backend agent adds the smallest service/schema/API surface needed for the feature.
3. Frontend agent adds the API client, page, and module navigation entry.
4. QA agent runs backend and frontend checks.
5. Foreman writes status output and keeps work reviewable.

## Safety Boundaries

- Do not submit bids.
- Do not send RFQs or external emails.
- Do not spend money.
- Do not approve contracts.
- Do not merge pull requests automatically.
- Do not change secrets.

## Role Reference

{role_summary}

## Roadmap Context Snapshot

{roadmap[:2000]}
"""


if __name__ == "__main__":
    sys.exit(main())
